# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_version6.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QSizePolicy, QFrame


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 739)
        MainWindow.setStyleSheet("background:rgb(28, 33, 38)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        #



        #
        self.Buttons_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Buttons_Frame.setMinimumSize(QtCore.QSize(70, 0))
        self.Buttons_Frame.setMaximumSize(QtCore.QSize(70, 16777215))

        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.Buttons_Frame.sizePolicy().hasHeightForWidth())

        self.Buttons_Frame.setFrameShape(QFrame.NoFrame)


        self.Buttons_Frame.setStyleSheet("QPushButton{\n"
                                         "padding:5px10px;\n"
                                         "border: none;\n"
                                         "border-radius:10px;\n"
                                         "background-color:black;\n"
                                         "color:white;\n"
                                         "width: 41px;\n"
                                         "height:40px;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "      background-color:rgb(163, 179, 184);\n"
                                         "}\n"
                                         "QPushButton:pressed {\n"
                                         "  background-color: rgb(85, 170, 255);\n"
                                         "}\n"
                                         "\n"
                                         "                             \n"
                                         "\n"
                                         "")
        self.Buttons_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Buttons_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Buttons_Frame.setObjectName("Buttons_Frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Buttons_Frame)

        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_check = QtWidgets.QPushButton(self.Buttons_Frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_check.setFont(font)
        self.btn_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_check.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/loupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_check.setIcon(icon)
        self.btn_check.setFlat(False)
        self.btn_check.setObjectName("btn_check")
        self.verticalLayout_2.addWidget(self.btn_check)
        self.btn_upload = QtWidgets.QPushButton(self.Buttons_Frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_upload.setFont(font)
        self.btn_upload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_upload.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/Updatedataset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_upload.setIcon(icon1)
        self.btn_upload.setObjectName("btn_upload")
        self.verticalLayout_2.addWidget(self.btn_upload)
        self.btn_update = QtWidgets.QPushButton(self.Buttons_Frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_update.setFont(font)
        self.btn_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_update.setStyleSheet("")
        self.btn_update.setIcon(icon1)
        self.btn_update.setObjectName("btn_update")
        self.verticalLayout_2.addWidget(self.btn_update)
        self.btn_issue = QtWidgets.QPushButton(self.Buttons_Frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_issue.setFont(font)
        self.btn_issue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_issue.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/1317755.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_issue.setIcon(icon2)
        self.btn_issue.setIconSize(QtCore.QSize(16, 16))
        self.btn_issue.setObjectName("btn_issue")
        self.verticalLayout_2.addWidget(self.btn_issue)
        self.gridLayout_3.addWidget(self.Buttons_Frame, 1, 0, 1, 2)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("background:transparent;")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centra_items = QtWidgets.QFrame(self.main_body)
        self.centra_items.setStyleSheet("background:rgb(44, 49, 60);\n"
                                        "")
        self.centra_items.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centra_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centra_items.setObjectName("centra_items")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centra_items)
        self.verticalLayout_3.setContentsMargins(4, 0, 4, 9)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centra_items)
        self.stackedWidget.setStyleSheet("backgorund:rgb(44, 49, 60)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.label_7 = QtWidgets.QLabel(self.main_page)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.main_page)
        self.check_page = QtWidgets.QWidget()
        self.check_page.setObjectName("check_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.check_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.check_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(85, 170, 255)")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.check_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(85, 170, 255)")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.check_page)
        self.lineEdit_2.setStyleSheet("background-color:rgb(28, 33, 38);\n"
                                      "color:white;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.btn_findDataset = QtWidgets.QPushButton(self.check_page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_findDataset.setFont(font)
        self.btn_findDataset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_findDataset.setStyleSheet("QPushButton{\n"
                                           "\n"
                                           "background-color:rgb(52, 59, 72);\n"
                                           "color:white;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "background-color: rgb(57, 65, 80);\n"
                                           "    border: 2px solid rgb(61, 70, 86);\n"
                                           "}\n"
                                           "QPushButton:pressed {    \n"
                                           "    background-color: rgb(35, 40, 49);\n"
                                           "}    border: 2px solid rgb(43, 50, 61);")
        self.btn_findDataset.setIcon(icon)
        self.btn_findDataset.setObjectName("btn_findDataset")
        self.horizontalLayout_3.addWidget(self.btn_findDataset)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.check_page)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 400))
        self.textEdit_2.setStyleSheet("background-color:rgb(28, 33, 38);\n"
                                      "color:white;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_6.addWidget(self.textEdit_2)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.check_page)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser_2.setStyleSheet("background-color:rgb(28, 33, 38);\n"
                                         "color:white;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_6.addWidget(self.textBrowser_2)
        self.stackedWidget.addWidget(self.check_page)
        self.upload_page = QtWidgets.QWidget()
        self.upload_page.setObjectName("upload_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.upload_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_uploadPagetitle = QtWidgets.QLabel(self.upload_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_uploadPagetitle.setFont(font)
        self.lbl_uploadPagetitle.setStyleSheet("color:rgb(85, 170, 255)")
        self.lbl_uploadPagetitle.setObjectName("lbl_uploadPagetitle")
        self.verticalLayout_5.addWidget(self.lbl_uploadPagetitle)
        self.frame = QtWidgets.QFrame(self.upload_page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setStyleSheet("background-color:rgb(28, 33, 38);\n"
                                    "color:white;")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(602, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_fileName = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fileName.setFont(font)
        self.lbl_fileName.setStyleSheet("color:rgb(85, 170, 255)")
        self.lbl_fileName.setObjectName("lbl_fileName")
        self.horizontalLayout_2.addWidget(self.lbl_fileName)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setStyleSheet("background-color:rgb(28, 33, 38);\n"
                                    "color:white;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "\n"
                                      "background-color:rgb(52, 59, 72);\n"
                                      "color:white;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "background-color: rgb(57, 65, 80);\n"
                                      "    border: 2px solid rgb(61, 70, 86);\n"
                                      "}\n"
                                      "QPushButton:pressed {    \n"
                                      "    background-color: rgb(35, 40, 49);\n"
                                      "}    border: 2px solid rgb(43, 50, 61);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.btn_upload_2 = QtWidgets.QPushButton(self.frame)
        self.btn_upload_2.setStyleSheet("QPushButton{\n"
                                        "\n"
                                        "background-color:rgb(52, 59, 72);\n"
                                        "color:white;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "background-color: rgb(57, 65, 80);\n"
                                        "    border: 2px solid rgb(61, 70, 86);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(35, 40, 49);\n"
                                        "}    border: 2px solid rgb(43, 50, 61);")
        self.btn_upload_2.setObjectName("btn_upload_2")
        self.horizontalLayout_2.addWidget(self.btn_upload_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777211, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "\n"
                                        "background-color:rgb(52, 59, 72);\n"
                                        "color:white;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "background-color: rgb(57, 65, 80);\n"
                                        "    border: 2px solid rgb(61, 70, 86);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(35, 40, 49);\n"
                                        "}    border: 2px solid rgb(43, 50, 61);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.frame)
        self.textBrowser = QtWidgets.QTextBrowser(self.upload_page)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textBrowser.setStyleSheet("background-color:rgb(28, 33, 38);\n"
                                       "color:white;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_5.addWidget(self.textBrowser)
        self.stackedWidget.addWidget(self.upload_page)
        self.update_page = QtWidgets.QWidget()
        self.update_page.setObjectName("update_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.update_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_update = QtWidgets.QLabel(self.update_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_update.setFont(font)
        self.lbl_update.setStyleSheet("color:rgb(85, 170, 255);")
        self.lbl_update.setObjectName("lbl_update")
        self.verticalLayout.addWidget(self.lbl_update)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_fileName_3 = QtWidgets.QLabel(self.update_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fileName_3.setFont(font)
        self.lbl_fileName_3.setStyleSheet("color:rgb(85, 170, 255)")
        self.lbl_fileName_3.setObjectName("lbl_fileName_3")
        self.horizontalLayout_6.addWidget(self.lbl_fileName_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.update_page)
        self.lineEdit_5.setStyleSheet("background-color:rgb(28, 33, 38);\n"
                                      "color:white;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.update_page)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "\n"
                                        "background-color:rgb(52, 59, 72);\n"
                                        "color:white;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "background-color: rgb(57, 65, 80);\n"
                                        "    border: 2px solid rgb(61, 70, 86);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(35, 40, 49);\n"
                                        "}    border: 2px solid rgb(43, 50, 61);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.tableWidget = QtWidgets.QTableWidget(self.update_page)
        self.tableWidget.setStyleSheet("            QTableWidget {\n"
                                       "background-color: #000000; \n"
                                       "alternate-background-color: #222222; \n"
                                       "gridline-color: #AAAAAA; \n"
                                       "color: #FFFFFF;\n"
                                       "selected-color: white;\n"
                                       "selection-background-color: #FFC000; \n"
                                       "selection-color: #AA00FF\n"
                                       "} \n"
                                       "           QTableWidget QHeaderView { background-color: #00000000;}\n"
                                       "           QTableWidget QHeaderView::section { background-color: #444444; color: #FFFFFF; border: none; \n"
                                       "           Tborder-style: none;} \n"
                                       "           QTableWidget QHeaderView::section:checked { background-color: #FFC000; color: #000000;}\n"
                                       "           QHeaderView::section:horizontal { border-right: 1px solid #AAAAAA; }\n"
                                       "           QHeaderView::section:vertical { border-bottom: 1px solid #AAAAAA; }\n"
                                       "           QTableWidget QTableCornerButton::section {  background: #00000000;  border: 0px   }")
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton_3 = QtWidgets.QPushButton(self.update_page)
        self.pushButton_3.setStyleSheet("color:white\n"                            "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.stackedWidget.addWidget(self.update_page)
        self.issue_opage = QtWidgets.QWidget()
        self.issue_opage.setObjectName("issue_opage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.issue_opage)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.issue_opage)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_Report = QtWidgets.QLabel(self.frame_2)
        self.title_Report.setMinimumSize(QtCore.QSize(100, 0))
        self.title_Report.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_Report.setFont(font)
        self.title_Report.setStyleSheet("color: rgb(85, 170, 255);")
        self.title_Report.setObjectName("title_Report")
        self.gridLayout_2.addWidget(self.title_Report, 0, 0, 1, 1)
        self.lbl_pic_1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_pic_1.setStyleSheet("background:transparent;")
        self.lbl_pic_1.setObjectName("lbl_pic_1")
        self.lbl_pic_1.setMinimumSize(QtCore.QSize(20, 20))
        self.gridLayout_2.addWidget(self.lbl_pic_1, 1, 0, 1, 1)
        self.lbl_filler = QtWidgets.QLabel(self.frame_2)
        self.lbl_filler.setObjectName("lbl_filler")
        self.gridLayout_2.addWidget(self.lbl_filler, 0, 1, 1, 1)
        self.lbl_pic_2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_pic_2.setStyleSheet("background:transparent;")
        self.lbl_pic_2.setObjectName("lbl_pic_2")
        self.lbl_pic_2.setMinimumSize(QtCore.QSize(20, 20))
        self.gridLayout_2.addWidget(self.lbl_pic_2, 1, 1, 1, 1)
        self.lbl_title1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_title1.setObjectName(u"lbl_title1")
        self.lbl_title1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_title1.setStyleSheet(u"color: white;\n"
                                      "")

        self.gridLayout_2.addWidget(self.lbl_title1, 2, 0, 1, 1)

        self.lbl_title2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_title2.setObjectName(u"lbl_title2")
        self.lbl_title2.setStyleSheet(u"color: white;")
        self.gridLayout_2.addWidget(self.lbl_title2, 2, 1, 1, 1)

        self.btn_downloadReport = QtWidgets.QPushButton(self.frame_2)
        self.btn_downloadReport.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_downloadReport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_downloadReport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_downloadReport.setAutoFillBackground(False)
        self.btn_downloadReport.setStyleSheet("QPushButton{\n"
                                              "\n"
                                              "background-color:rgb(52, 59, 72);\n"
                                              "color:white;\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "background-color: rgb(57, 65, 80);\n"
                                              "    border: 2px solid rgb(61, 70, 86);\n"
                                              "}\n"
                                              "QPushButton:pressed {    \n"
                                              "    background-color: rgb(35, 40, 49);\n"
                                              "}    border: 2px solid rgb(43, 50, 61);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Images/pdfs-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_downloadReport.setIcon(icon4)
        self.btn_downloadReport.setIconSize(QtCore.QSize(20, 20))
        self.btn_downloadReport.setObjectName("btn_downloadReport")
        self.gridLayout_2.addWidget(self.btn_downloadReport, 3, 1, 1, 1)
        self.btn_issue_view = QtWidgets.QPushButton(self.frame_2)
        self.btn_issue_view.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_issue_view.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_issue_view.setStyleSheet("QPushButton{\n"
                                          "\n"
                                          "background-color:rgb(52, 59, 72);\n"
                                          "color:white;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "background-color: rgb(57, 65, 80);\n"
                                          "    border: 2px solid rgb(61, 70, 86);\n"
                                          "}\n"
                                          "QPushButton:pressed {    \n"
                                          "    background-color: rgb(35, 40, 49);\n"
                                          "}    border: 2px solid rgb(43, 50, 61);\n"
                                          "")
        self.btn_issue_view.setIconSize(QtCore.QSize(20, 20))
        self.btn_issue_view.setObjectName("btn_issue_view")
        self.gridLayout_2.addWidget(self.btn_issue_view, 3, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.issue_opage)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.centra_items)
        self.gridLayout_3.addWidget(self.main_body, 1, 2, 1, 1)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMinimumSize(QtCore.QSize(0, 30))
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_footer.setStyleSheet("background:rgb(33, 37, 43);")
        self.main_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main_footer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.main_footer)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.main_footer)
        self.label_2.setMinimumSize(QtCore.QSize(50, 30))
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setStyleSheet("color:rgb(170, 170, 127);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.gridLayout_3.addWidget(self.main_footer, 2, 0, 1, 3)
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMinimumSize(QtCore.QSize(0, 70))
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 70))
        self.main_header.setStyleSheet("background:rgb(33, 37, 43);")
        self.main_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.main_header)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 255, 127)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("prelaunch_forecaster1.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.gridLayout_3.addWidget(self.main_header, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_check.setText(_translate("MainWindow", "Check Datasets"))
        self.btn_upload.setText(_translate("MainWindow", "Upload Datasets"))
        self.btn_update.setText(_translate("MainWindow", "Update a Dataset"))
        self.btn_issue.setText(_translate("MainWindow", "Issue Report   "))
        self.label_7.setText(_translate("MainWindow", "Home Page"))
        self.label_11.setText(_translate("MainWindow", "Check for Datasets"))
        self.label_12.setText(_translate("MainWindow", "Find Dataset"))
        self.btn_findDataset.setText(_translate("MainWindow", "Find"))
        self.lbl_uploadPagetitle.setText(_translate("MainWindow", "Upload Datasets"))
        self.lbl_fileName.setText(_translate("MainWindow", "File Name"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.btn_upload_2.setText(_translate("MainWindow", "Upload"))
        self.pushButton_2.setText(_translate("MainWindow", "Write Doc"))
        self.lbl_update.setText(_translate("MainWindow", "Update Datasets"))
        self.lbl_fileName_3.setText(_translate("MainWindow", "File Name"))
        self.pushButton_5.setText(_translate("MainWindow", "Browse"))

        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.title_Report.setText(_translate("MainWindow", "Issue Report"))

        self.btn_downloadReport.setText(_translate("MainWindow", "Download Report"))
        self.btn_issue_view.setText(_translate("MainWindow", "View Graphs"))
        self.label_2.setText(_translate("MainWindow", "v.1.0.0"))


import icon_cwt

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
