# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2_v6.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewGraphs(object):
    def setupUi(self, ViewGraphs):
        ViewGraphs.setObjectName("ViewGraphs")
        ViewGraphs.resize(800, 585)
        ViewGraphs.setStyleSheet("background:rgb(28, 33, 38)")
        self.centralwidget = QtWidgets.QWidget(ViewGraphs)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pic1 = QtWidgets.QLabel(self.centralwidget)
        self.pic1.setStyleSheet("color:white\n"
"")
        self.pic1.setObjectName("pic1")
        self.horizontalLayout.addWidget(self.pic1)
        self.pic2 = QtWidgets.QLabel(self.centralwidget)
        self.pic2.setStyleSheet("color:white;")
        self.pic2.setObjectName("pic2")
        self.horizontalLayout.addWidget(self.pic2)
        ViewGraphs.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ViewGraphs)
        self.statusbar.setObjectName("statusbar")
        ViewGraphs.setStatusBar(self.statusbar)

        self.retranslateUi(ViewGraphs)
        QtCore.QMetaObject.connectSlotsByName(ViewGraphs)

    def retranslateUi(self, ViewGraphs):
        _translate = QtCore.QCoreApplication.translate
        ViewGraphs.setWindowTitle(_translate("ViewGraphs", "Graphs"))
        self.pic1.setText(_translate("ViewGraphs", "TextLabel"))
        self.pic2.setText(_translate("ViewGraphs", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewGraphs = QtWidgets.QMainWindow()
    ui = Ui_ViewGraphs()
    ui.setupUi(ViewGraphs)
    ViewGraphs.show()
    sys.exit(app.exec_())
